[neat]
population_size = 100

[neat.speciation]
target_species_count = 10
factor_weights = 1.0
factor_genes = 1.0
factor_activations = 1.0

[genome.structure]
number_of_inputs = 5
number_of_outputs = 1
percent_of_connected_inputs = 1.0
outputs_activation = "Sigmoid"
seed = 12

[[genome.mutations]]
type = "add_connection"
chance = 0.1

[[genome.mutations]]
type = "add_recurrent_connection"
chance = 0.01

[[genome.mutations]]
type = "add_node"
chance = 0.05
activation_pool = [
    "Sigmoid",
    "Tanh",
    "Relu",
    "Linear",
    "Gaussian",
    "Step",
    "Sine",
    "Cosine",
    "Inverse",
    "Absolute",
]

[[genome.mutations]]
type = "remove_node"
chance = 0.0001

[[genome.mutations]]
type = "change_weights"
chance = 0.95
percent_perturbed = 0.5
standard_deviation = 0.1

[[genome.mutations]]
type = "change_activation"
chance = 0.05
activation_pool = [
    "Sigmoid",
    "Tanh",
    "Relu",
    "Linear",
    "Gaussian",
    "Step",
    "Sine",
    "Cosine",
    "Inverse",
    "Absolute",
]
