[package]
name = "just-neat"
version = "0.1.0"
authors = ["Silvan Buedenbender <s.buedenbender@badgersystems.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "neat"
path = "src/lib.rs"

[[bin]]
name = "neat_example"
path = "src/example_XOR.rs"

[dependencies]
rand = { version = "0.7.3", features = [ "small_rng" ] }
serde = { version = "1.0", features = ["derive"] }
config = "0.9"
rayon = "1.3"
# favannat = { git = "https://github.com/SilvanCodes/favannat" }
favannat= { path = "../favannat" }


[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench_neat"
harness = false
