[neat]
population_size = 300

[neat.speciation]
target_species_count = 30 # number of desired species
factor_weights = 1.5 # factor for percent of different genes
factor_genes = 1.5 # weight difference factor
factor_activations = 1.0 # factor for percent of different activations

[genome.structure]
number_of_inputs = 7
number_of_outputs = 1
percent_of_connected_inputs = 1.0
outputs_activation = "Tanh"
seed = 12

[[genome.mutations]]
type = "add_connection"
chance = 0.1

[[genome.mutations]]
type = "add_recurrent_connection"
chance = 0.01

[[genome.mutations]]
type = "add_node"
chance = 0.005
activation_pool = [
    "Sigmoid",
    "Tanh",
    "Relu",
    "Linear",
    "Gaussian",
    "Step",
    "Sine",
    "Cosine",
    "Inverse",
    "Absolute",
]

[[genome.mutations]]
type = "change_weights"
chance = 1.0
percent_perturbed = 0.5
standard_deviation = 0.1

[[genome.mutations]]
type = "change_activation"
chance = 0.05
activation_pool = [
    "Sigmoid",
    "Tanh",
    "Relu",
    "Linear",
    "Gaussian",
    "Step",
    "Sine",
    "Cosine",
    "Inverse",
    "Absolute",
]
