[neat]
population_size = 100

[neat.reproduction]
survival_rate = 0.2 # allow the top x percent of species to survive and reproduce
generations_until_stale = 10 # number of generations allowed without improvement (stale species are reproduced only by the top performing member)
elitism_species = 1
elitism_individuals = 0

[neat.speciation]
target_species_count = 10 # number of desired species
factor_weights = 0.1 # factor for percent of different genes
factor_genes = 2.0 # weight difference factor
factor_activations = 1.0 # factor for percent of different activations

[genome.structure]
inputs = 3
inputs_connected_percent = 1.0
outputs = 1
outputs_activation = "Sigmoid"
weight_std_dev = 3.0
weight_cap = 9.0

[[genome.mutations]]
type = "add_connection"
chance = 0.1

[[genome.mutations]]
type = "add_node"
chance = 0.05
activation_pool = [
    "Sigmoid",
    "Tanh",
    "Relu",
    "Linear",
    "Gaussian",
    "Step",
    "Sine",
    "Cosine",
    "Inverse",
    "Absolute",
]

[[genome.mutations]]
type = "change_weights"
chance = 1.0
percent_perturbed = 0.5

[[genome.mutations]]
type = "change_activation"
chance = 0.05
activation_pool = [
    "Sigmoid",
    "Tanh",
    "Relu",
    "Linear",
    "Gaussian",
    "Step",
    "Sine",
    "Cosine",
    "Inverse",
    "Absolute",
]
