[neat]
population_size = 1000

[neat.reproduction]
survival_rate = 0.1 # allow the top x percent of species to survive and reproduce
generations_until_stale = 10 # number of generations allowed without improvement (stale species are reproduced only by the top performing member)
elitism_species = 1
elitism_individuals = 0

[neat.speciation]
target_species_count = 25 # number of desired species
factor_weights = 2.0 # factor for percent of different genes
factor_genes = 3.0 # weight difference factor
factor_activations = 1.0 # factor for percent of different activations

[genome.structure]
number_of_inputs = 9
number_of_outputs = 4
percent_of_connected_inputs = 1.0
outputs_activation = "Tanh"
seed = 12

[[genome.mutations]]
type = "add_connection"
chance = 0.03

[[genome.mutations]]
type = "add_recurrent_connection"
chance = 0.01

[[genome.mutations]]
type = "add_node"
chance = 0.02
activation_pool = [
    # "Sigmoid",
    # "Tanh",
    "Relu",
    # "Linear",
    # "Gaussian",
    # "Step",
    # "Sine",
    # "Cosine",
    # "Inverse",
    # "Absolute",
]

[[genome.mutations]]
type = "change_weights"
chance = 0.5
percent_perturbed = 0.5
standard_deviation = 0.1

# [[genome.mutations]]
# type = "change_activation"
# chance = 0.01
# activation_pool = [
#     "Sigmoid",
#     "Tanh",
#     "Relu",
#     "Linear",
#     "Gaussian",
#     "Step",
#     "Sine",
#     "Cosine",
#     "Inverse",
#     "Absolute",
# ]
