[neat]
population_size = 250

[neat.speciation]
target_species_count = 25
factor_weights = 2.0
factor_genes = 3.0
factor_activations = 1.0

[genome.structure]
inputs = 25
outputs = 4
inputs_connected_percent = 1.0
outputs_activation = "Tanh"
weight_std_dev = 0.1
weight_cap = 1.0

[[genome.mutations]]
type = "add_connection"
chance = 0.1

[[genome.mutations]]
type = "add_recurrent_connection"
chance = 0.01

[[genome.mutations]]
type = "add_node"
chance = 0.005
activation_pool = [
    "Sigmoid",
    "Tanh",
    "Relu",
    "Linear",
    "Gaussian",
    "Step",
    "Sine",
    "Cosine",
    "Inverse",
    "Absolute",
]

[[genome.mutations]]
type = "remove_node"
chance = 0.0001

[[genome.mutations]]
type = "change_weights"
chance = 0.95
percent_perturbed = 0.25

[[genome.mutations]]
type = "change_activation"
chance = 0.05
activation_pool = [
    "Sigmoid",
    "Tanh",
    "Relu",
    "Linear",
    "Gaussian",
    "Step",
    "Sine",
    "Cosine",
    "Inverse",
    "Absolute",
]
