refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
  progress:
    kind: file
    path: "examples/BipedalWalker-v3/progress.log"
    encoder:
      pattern: "{d} - {m}{n}"
root:
  level: info
  appenders:
    - stdout
    - progress
