[neat]
population_size = 100

[neat.speciation]
target_species_count = 10 # number of desired species
factor_weights = 1.0 # factor for percent of different genes
factor_genes = 1.0 # weight difference factor
factor_activations = 1.0 # factor for percent of different activations

[genome.structure]
inputs = 3
outputs = 1
inputs_connected_percent = 1.0
outputs_activation = "Tanh"
weight_std_dev = 1.0
weight_cap = 3.0

[[genome.mutations]]
type = "add_connection"
chance = 0.1

[[genome.mutations]]
type = "add_recurrent_connection"
chance = 0.01

[[genome.mutations]]
type = "add_node"
chance = 0.05
activation_pool = [
    "Sigmoid",
    "Tanh",
    "Relu",
    "Linear",
    "Gaussian",
    "Step",
    "Sine",
    "Cosine",
    "Inverse",
    "Absolute",
]

[[genome.mutations]]
type = "change_weights"
chance = 1.0
percent_perturbed = 0.5

[[genome.mutations]]
type = "change_activation"
chance = 0.05
activation_pool = [
    "Sigmoid",
    "Tanh",
    "Relu",
    "Linear",
    "Gaussian",
    "Step",
    "Sine",
    "Cosine",
    "Inverse",
    "Absolute",
]
