seed = 123

[setup]
population = 100 # number of networks

[setup.dimension]
input = 3 # number inputs
output = 1 # number outputs

[initialization]
output = "Tanh" # activation function of output nodes
activations = [
    "Linear",
    "Sigmoid",
    "Tanh",
    "Gaussian",
    "Step",
    "Sine",
    "Cosine",
    "Inverse",
    "Absolute",
    "Relu",
    # "Squared",
] # pool of activation functions to choose from
connections = 0.5 # percent of inputs fully connected to outputs

[reproduction]
surviving = 0.2 # allow the top x percent of species to survive and reproduce
stale_after = 15 # number of generations allowed without improvement (stale species go extinct)
elitism_species = 1
elitism_individuals = 0

[mutation]
gene_node = 0.05 # chance of adding a new node gene
gene_connection = 0.1 # chance of adding a new connection gene
recurrent = 0.3
activation_change = 0.075

[mutation.weights]
percent_min = 0.6
percent_max = 0.9
random = 0.0
perturbation_range = 1.5
distribution = "Uniform"

[compatability]
target_species = 8 # number of desired species
threshold = 0.5 # difference above threshold is considered incompatible
threshold_delta = 0.002 # adjust threshold by at least x if num species unequal target species
factor_genes = 2.0 # factor for percent of different genes
factor_weights = 0.1 # weight difference factor
factor_activations = 1.0 # factor for percent of different activations

[novelty]
cap = 0.0
nearest_neighbors = 15
impatience = 5
demanded_increase_percent = 0 # std dev required of agent raw fitness
