[setup]
population = 250 # number of networks
output_activation = "Tanh"

[setup.dimension]
input = 3 # number inputs
output = 1 # number outputs

[reproduction]
stale_after = 15 # number of generations allowed without improvement (stale species are reproduced only by the top performing member)
offspring_from_crossover = 0.75 # proportion of offspring that results from crossover
offspring_from_crossover_interspecies = 0.001 # proportion of crossover that is interspecies
surviving = 0.3 # allow the top x percent of species to survive and reproduce

[mutation]
gene_node = 0.03 # chance of adding a new node gene
gene_connection = 0.05 # chance of adding a new connection gene
weight = 0.8 # chance of mutating all weights of a genome
weight_random = 0.1 # chance that a mutated weight is replaced by a random one
weight_perturbation = 5.0 # amount of perturbation (step up or down)
weight_distribution = "Uniform" # probability distribution of perturbation
activation_strategy = "FixedTanh" # initial activation function of nodes
activation_change = 0.0

[compatability]
target_species = 25 # number of desired species
threshold = 5.0 # difference above threshold is considered incompatible
threshold_delta = 0.3 # adjust threshold by x if num species unequal target species
factor_genes = 10.0 # factor for percent of different genes
factor_weights = 0.1 # weight difference factor
factor_activations = 15.0 # factor for percent of different activations