[setup]
population = 150 # number of networks

[setup.dimension]
input = 3 # number inputs
output = 1 # number outputs

[initialization]
output = "Sigmoid" # activation function of output nodes
activations = [
    # "Linear",
    "Sigmoid",
    # "Tanh",
    # "Gaussian",
    # "Step",
    # "Sine",
    # "Cosine",
    # "Inverse",
    # "Absolute",
    # "Relu",
    # "Squared",
] # pool of activation functions to choose from
connections = 1.0 # percent of inputs fully connected to outputs
weights = "Random" # initial value of weights

[reproduction]
surviving = 0.2 # allow the top x percent of species to survive and reproduce
stale_after = 15 # number of generations allowed without improvement (stale species are reproduced only by the top performing member)

[mutation]
gene_node = 0.03 # chance of adding a new node gene
gene_connection = 0.05 # chance of adding a new connection gene
recurrent = 0.0 # chanche of a new connection being a recurrent one
weight = 0.8 # chance of mutating all weights of a genome
weight_random = 0.1 # chance that a mutated weight is replaced by a totally random one
weight_perturbation = 3.0 # amount of perturbation (step up or down, uniformly distibuted)
weight_distribution = "Uniform"
activation_change = 0.05

[compatability]
target_species = 15 # number of desired species
threshold = 1.0 # difference above threshold is considered incompatible
threshold_delta = 0.005 # adjust threshold by x if num species unequal target species
factor_genes = 2.5 # factor for percent of different genes
factor_weights = 1.0 # weight difference factor
factor_activations = 0.5 # factor for percent of different activations
