[setup]
population = 150 # number of networks
output_activation = "Sigmoid"

[setup.dimension]
input = 3 # number inputs
output = 1 # number outputs

[reproduction]
offspring_from_crossover = 0.75 # proportion of offspring that results from crossover
offspring_from_crossover_interspecies = 0.001 # proportion of crossover that is interspecies
surviving = 0.4 # allow the top x percent of species to survive and reproduce
stale_after = 15 # number of generations allowed without improvement (stale species are reproduced only by the top performing member)

[mutation]
gene_node = 0.03 # chance of adding a new node gene
gene_connection = 0.05 # chance of adding a new connection gene
weight = 0.8 # chance of mutating all weights of a genome
weight_random = 0.1 # chance that a mutated weight is replaced by a totally random one
weight_perturbation = 5.0 # amount of perturbation (step up or down, uniformly distibuted)
weight_distribution = "Uniform"
activation_strategy = "Random"
activation_change = 0.3

[compatability]
target_species = 15 # number of desired species
threshold = 5.0 # difference above threshold is considered incompatible
threshold_delta = 0.3 # adjust threshold by x if num species unequal target species
factor_genes = 10.0 # factor for percent of different genes
factor_weights = 0.1 # weight difference factor
factor_activations = 15.0 # factor for percent of different activations
