required_fitness = 0.0

[setup]
population = 150 # number of networks
output_activation = "Tanh"

[setup.dimension]
input = 3 # number inputs
output = 1 # number outputs

[initialization]
output = "Tanh" # activation function of output nodes
activations = ["Tanh"] # pool of activation functions to choose from
connections = 1.0 # percent of inputs fully connected to outputs

[reproduction]
stale_after = 15 # number of generations allowed without improvement (stale species are reproduced only by the top performing member)
surviving = 0.25 # allow the top x percent of species to survive and reproduce
elitism_species = 1
elitism_individuals = 0

[mutation]
gene_node = 0.03 # chance of adding a new node gene
gene_connection = 0.05 # chance of adding a new connection gene
recurrent = 0.0
activation_change = 0.1

[mutation.weights]
percent_min = 0.6
percent_max = 1.0
random = 0.0
perturbation_range = 0.1
distribution = "Uniform"

[compatability]
target_species = 15 # number of desired species
threshold = 5.5 # difference above threshold is considered incompatible
threshold_delta = 0.3 # adjust threshold by x if num species unequal target species
factor_genes = 10.0 # factor for number of different genes
factor_weights = 0.1 # weight difference factor
factor_activations = 15.0

[novelty]
cap = 0.0
nearest_neighbors = 15
archive_threshold = 3
impatience = 5
demanded_increase_percent = 1.0 # percentage increase required of agent raw fitness
