[setup]
population = 150 # number of networks
output_activation = "Tanh"

[setup.dimension]
input = 3 # number inputs
output = 1 # number outputs

[initialization]
output = "Tanh" # activation function of output nodes
activations = ["Tanh"] # pool of activation functions to choose from
connections = 1.0 # percent of inputs fully connected to outputs
weights = "Random"

[reproduction]
stale_after = 15 # number of generations allowed without improvement (stale species are reproduced only by the top performing member)
offspring_from_crossover = 0.75 # proportion of offspring that results from crossover
offspring_from_crossover_interspecies = 0.001 # proportion of crossover that is interspecies
surviving = 0.25 # allow the top x percent of species to survive and reproduce

[mutation]
gene_node = 0.03 # chance of adding a new node gene
gene_connection = 0.05 # chance of adding a new connection gene
recurrent = 0.0
weight = 0.8 # chance of mutating all weights of a genome
weight_random = 0.1 # chance that a mutated weight is replaced by a totally random one
weight_perturbation = 3.0 # amount of perturbation (step up or down)
weight_distribution = "Uniform" # probability distribution of perturbation
activation_strategy = "FixedTanh"
activation_change = 0.1

[compatability]
target_species = 15 # number of desired species
threshold = 5.5 # difference above threshold is considered incompatible
threshold_delta = 0.3 # adjust threshold by x if num species unequal target species
factor_genes = 10.0 # factor for number of different genes
factor_weights = 0.1 # weight difference factor
factor_activations = 15.0

[novelty]
nearest_neighbors = 15
archive_threshold = 3
